In [7]:
import numpy as np
from scipy import stats

In [13]:
arr = np.array([0, 0, 1, 3, 4, 0, 4, 3])

In [15]:
len(arr)

8

### ndarray中非0元素的个数

In [14]:
np.count_nonzero(arr)

5

In [16]:
np.count_nonzero(arr.reshape((2, 4)))

5

### flatten

In [17]:
arr.ravel()

array([0, 0, 1, 3, 4, 0, 4, 3])

In [18]:
arr.reshape((2, 4)).ravel()

array([0, 0, 1, 3, 4, 0, 4, 3])

## 描述性统计

In [3]:
arr = np.array([1, 9, 6, 4, 8, 5, 7, 3, 2, 8, 3, 8, 3, 9, 7, 9, 5, 1, 5, 3])

In [4]:
np.mean(arr)

5.3

In [5]:
np.median(arr)

5.0

In [6]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'

In [9]:
#np中没有直接求众数的方法
#bincount统计了每个索引位置出现的次数，注意arr的元素只能是正整数
#如结果第一个元素0表示0在arr中出现了0次
# #间接求众数
np.argmax(np.bincount(arr))

3

In [10]:
r = stats.mode(arr)  # 表示3出现了4次
r

ModeResult(mode=array([3]), count=array([4]))

In [11]:
r.mode

array([3])

In [12]:
r.count

array([4])