# 随机数简介
有两种产生随机数的方法
1. python自带的random模块
2. np.random模块

In [1]:
import random
import numpy as np

# 产生随机数

## 产生随机整数
### random.randint(a, b)
Return random integer in range [a, b], including both end points.

In [11]:
random.randint(0, 10)

10

### np.random.randint

In [13]:
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(0, 100, (5, ))

array([93,  5, 62, 46, 62])

### 生成各种分布的随机数

#### 均匀分布
##### np.random.rand
Create an array of the given shape and populate it with
random samples from a uniform distribution

In [1]:
import numpy as np

In [33]:
np.random.rand(5)

array([0.53888885, 0.00587379, 0.67315248, 0.21002426, 0.93255759])

In [34]:
np.random.rand(2, 3)

array([[0.37424475, 0.75241892, 0.763139  ],
       [0.87049946, 0.11011118, 0.30009198]])

# 随机采样

In [2]:
list1 = list(range(100))

In [17]:
random.sample(list1, 5)

[67, 31, 34, 94, 32]

## np.random.choice(a, size=None, replace=True, p=None)
这里的p是每个样本被采样到的可能性！

In [1]:
import numpy as np

In [3]:
np.random.choice(list1, 5)

array([71, 33,  8, 42, 94])

In [5]:
r = np.random.choice(list1, 1)
r

array([72])

In [9]:
r[0]

72

In [7]:
np.random.choice(list1, 5).squeeze()

array([32, 23, 73, 90, 31])

## 设置随机种子seed
* random.seed()
* numpy.random.seed()不是线程安全的，
* 如果程序中有多个线程最好使用numpy.random.RandomState实例对象来创建  或者使用random.seed()来设置相同的随机数种子。  
注意这几种方式不能交叉使用，  
如使用了random.seed()设置了种子，那么就要用random模块的方法生成随机数

In [20]:
random.seed(14)
random.sample(list1, 5)

[13, 78, 89, 96, 83]

In [21]:
random.seed(14)
random.sample(list1, 5)

[13, 78, 89, 96, 83]

In [22]:
random.sample(list1, 5)

[67, 31, 34, 94, 32]

In [27]:
np.random.seed(14)
np.random.choice(list1, 5)

array([88, 12, 22, 71, 28])

In [29]:
np.random.seed(14)
np.random.choice(list1, 5)

array([88, 12, 22, 71, 28])

In [32]:
np.random.RandomState(14).choice(list1, 5)

array([88, 12, 22, 71, 28])

In [5]:
np.random.RandomState(14).uniform(size=(5,2))

array([[0.51394334, 0.77316505],
       [0.87042769, 0.00804695],
       [0.30973593, 0.95760374],
       [0.51311671, 0.31828442],
       [0.53919994, 0.22125494]])

## 随机打乱

### 打乱list

In [7]:
ll = list(range(10))
random.shuffle(ll)
ll

[7, 0, 8, 3, 9, 5, 6, 1, 2, 4]

In [9]:
ll = list(range(10))
np.random.shuffle(ll)
ll

[9, 4, 2, 7, 5, 6, 0, 3, 8, 1]

In [6]:
arr = np.arange(15).reshape(5, 3)
arrlist = arr.tolist()
random.shuffle(arrlist)
arrlist

[[0, 1, 2], [9, 10, 11], [12, 13, 14], [6, 7, 8], [3, 4, 5]]

In [17]:
np.random.permutation(list(range(10)))

array([6, 5, 3, 2, 8, 1, 7, 4, 0, 9])

### 打乱ndarray

In [1]:
import numpy as np
arr = np.arange(15).reshape(5, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
np.random.shuffle(arr)
arr

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [7]:
arr = np.arange(15).reshape(5, 3)
np.random.permutation(arr)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 3,  4,  5]])

### 设置随机种子

In [20]:
arr = np.arange(15).reshape(5, 3)
rng = np.random.RandomState(14)
rng.shuffle(arr)
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 9, 10, 11]])

In [22]:
np.shape(arr)

(5, 3)

#### random.suffle结果有问题！

In [5]:
import random
random.shuffle(arr)
arr

array([[ 0,  1,  2],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 转换为list后没有问题