In [12]:
import random
import numpy as np

## 产生随机数

### 产生随机整数
#### random.randint(a, b)
Return random integer in range [a, b], including both end points.

In [11]:
random.randint(0, 10)

10

In [13]:
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(0, 100, (5, ))

array([93,  5, 62, 46, 62])

### 生成各种分布的随机数

#### 均匀分布
##### np.random.rand
Create an array of the given shape and populate it with
random samples from a uniform distribution

In [33]:
np.random.rand(5)

array([0.53888885, 0.00587379, 0.67315248, 0.21002426, 0.93255759])

In [34]:
np.random.rand(2, 3)

array([[0.37424475, 0.75241892, 0.763139  ],
       [0.87049946, 0.11011118, 0.30009198]])

## 随机采样

In [15]:
list1 = list(range(100))

In [17]:
random.sample(list1, 5)

[67, 31, 34, 94, 32]

In [31]:
np.random.choice(list1, 5)

array([87, 32,  4, 77, 10])

## 设置随机种子seed
* random.seed()
* numpy.random.seed()不是线程安全的，
* 如果程序中有多个线程最好使用numpy.random.RandomState实例对象来创建  或者使用random.seed()来设置相同的随机数种子。  
注意这几种方式不能交叉使用，  
如使用了random.seed()设置了种子，那么就要用random模块的方法生成随机数

In [20]:
random.seed(14)
random.sample(list1, 5)

[13, 78, 89, 96, 83]

In [21]:
random.seed(14)
random.sample(list1, 5)

[13, 78, 89, 96, 83]

In [22]:
random.sample(list1, 5)

[67, 31, 34, 94, 32]

In [27]:
np.random.seed(14)
np.random.choice(list1, 5)

array([88, 12, 22, 71, 28])

In [29]:
np.random.seed(14)
np.random.choice(list1, 5)

array([88, 12, 22, 71, 28])

In [32]:
np.random.RandomState(14).choice(list1, 5)

array([88, 12, 22, 71, 28])

## 随机打乱

### 打乱list

In [7]:
ll = list(range(10))
random.shuffle(ll)
ll

[7, 0, 8, 3, 9, 5, 6, 1, 2, 4]

In [9]:
ll = list(range(10))
np.random.shuffle(ll)
ll

[9, 4, 2, 7, 5, 6, 0, 3, 8, 1]

In [6]:
arr = np.arange(15).reshape(5, 3)
arrlist = arr.tolist()
random.shuffle(arrlist)
arrlist

[[0, 1, 2], [9, 10, 11], [12, 13, 14], [6, 7, 8], [3, 4, 5]]

In [17]:
np.random.permutation(list(range(10)))

array([6, 5, 3, 2, 8, 1, 7, 4, 0, 9])

### 打乱ndarray

In [11]:
import numpy as np
arr = np.arange(15).reshape(5, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
np.random.shuffle(arr)

In [15]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
arr = np.arange(15).reshape(5, 3)
np.random.permutation(arr)

array([[ 9, 10, 11],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12, 13, 14],
       [ 0,  1,  2]])

#### random.suffle结果有问题！

In [5]:
import random
random.shuffle(arr)
arr

array([[ 0,  1,  2],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 转换为list后没有问题