In [9]:
# !pip install tensorflow -U
!pip freeze | grep tensorflow

tensorflow==2.0.0
tensorflow-estimator==2.0.1


# tf2相对于tf1的改进
https://tensorflow.google.cn/guide/effective_tf2
## API Cleanup
Many APIs are either gone or moved in TF 2.0. Some of the major changes include removing tf.app, tf.flags, and tf.logging in favor of the now open-source absl-py, rehoming projects that lived in tf.contrib, and cleaning up the main tf.* namespace by moving lesser used functions into subpackages like tf.math. Some APIs have been replaced with their 2.0 equivalents - tf.summary, tf.keras.metrics, and tf.keras.optimizers.
## Eager execution
In Tensorflow 2.0, eager execution is enabled by default.
## No more globals

## Functions, not sessions




# tf.keras
https://tensorflow.google.cn/api_docs/python/tf/keras

In [18]:
import tensorflow as tf
from tensorflow import keras

In [17]:
print(tf.__version__)

2.0.0


## Build a simple model--Sequential model

In [19]:
from tensorflow.keras import layers

model = tf.keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(layers.Dense(64, activation='relu'))
# Add another:
model.add(layers.Dense(64, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(layers.Dense(10, activation='softmax'))

### Configure the layers
* activation: Set the activation function for the layer. This parameter is specified by the name of a built-in function or as a callable object. By default, no activation is applied.
* kernel_initializer and bias_initializer: The initialization schemes that create the layer's weights (kernel and bias). This parameter is a name or a callable object. This defaults to the "Glorot uniform" initializer.
* kernel_regularizer and bias_regularizer: The regularization schemes that apply the layer's weights (kernel and bias), such as L1 or L2 regularization. By default, no regularization is applied.

In [20]:
# Create a sigmoid layer:
layers.Dense(64, activation='sigmoid')
# Or:
layers.Dense(64, activation=tf.keras.activations.sigmoid)

# A linear layer with L1 regularization of factor 0.01 applied to the kernel matrix:
layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# A linear layer with L2 regularization of factor 0.01 applied to the bias vector:
layers.Dense(64, bias_regularizer=tf.keras.regularizers.l2(0.01))

# A linear layer with a kernel initialized to a random orthogonal matrix:
layers.Dense(64, kernel_initializer='orthogonal')

# A linear layer with a bias vector initialized to 2.0s:
layers.Dense(64, bias_initializer=tf.keras.initializers.Constant(2.0))

### Train and evaluate

In [21]:
model = tf.keras.Sequential([
# Adds a densely-connected layer with 64 units to the model:
layers.Dense(64, activation='relu', input_shape=(32,)),
# Add another:
layers.Dense(64, activation='relu'),
# Add a softmax layer with 10 output units:
layers.Dense(10, activation='softmax')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

tf.keras.Model.compile takes three important arguments:

* optimizer: This object specifies the training procedure. Pass it optimizer instances from the tf.keras.optimizers module, such as tf.keras.optimizers.Adam or tf.keras.optimizers.SGD. If you just want to use the default parameters, you can also specify optimizers via strings, such as 'adam' or 'sgd'.
* loss: The function to minimize during optimization. Common choices include mean square error (mse), categorical_crossentropy, and binary_crossentropy. Loss functions are specified by name or by passing a callable object from the tf.keras.losses module.
* metrics: Used to monitor training. These are string names or callables from the tf.keras.metrics module.
* Additionally, to make sure the model trains and evaluates eagerly, you can make sure to pass run_eagerly=True as a parameter to compile.

The following shows a few examples of configuring a model for training:

In [ ]:
# Configure a model for mean-squared error regression.
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss='mse',       # mean squared error
              metrics=['mae'])  # mean absolute error

# Configure a model for categorical classification.
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.01),
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=[tf.keras.metrics.CategoricalAccuracy()])

### Train from NumPy data

In [22]:
import numpy as np

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.fit(data, labels, epochs=10, batch_size=32)

Train on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 1s 660us/sample - loss: 25.7322 - accuracy: 0.1130
Epoch 2/10
1000/1000 [==============================] - 0s 59us/sample - loss: 208.8320 - accuracy: 0.1120
Epoch 3/10
1000/1000 [==============================] - 0s 50us/sample - loss: 929.5049 - accuracy: 0.1030
Epoch 4/10
1000/1000 [==============================] - 0s 50us/sample - loss: 1703.7768 - accuracy: 0.0990
Epoch 5/10
1000/1000 [==============================] - 0s 57us/sample - loss: 4012.0033 - accuracy: 0.1060
Epoch 6/10
1000/1000 [==============================] - 0s 46us/sample - loss: 7791.5488 - accuracy: 0.1070
Epoch 7/10
1000/1000 [==============================] - 0s 52us/sample - loss: 11280.8306 - accuracy: 0.0840
Epoch 8/10
1000/1000 [==============================] - 0s 49us/sample - loss: 20020.8224 - accuracy: 0.0890
Epoch 9/10
1000/1000 [==============================] - 0s 43us/sample - loss: 19549.7783 - accuracy: 0.1080
Epoch 

Here's an example using validation_data:

In [23]:
import numpy as np

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

val_data = np.random.random((100, 32))
val_labels = np.random.random((100, 10))

model.fit(data, labels, epochs=10, batch_size=32,
          validation_data=(val_data, val_labels))

Train on 1000 samples, validate on 100 samples
Epoch 1/10
1000/1000 [==============================] - 0s 148us/sample - loss: 40965.3121 - accuracy: 0.1060 - val_loss: 54195.8666 - val_accuracy: 0.0400
Epoch 2/10
1000/1000 [==============================] - 0s 81us/sample - loss: 49548.4699 - accuracy: 0.1050 - val_loss: 41730.7855 - val_accuracy: 0.1300
Epoch 3/10
1000/1000 [==============================] - 0s 88us/sample - loss: 50720.4791 - accuracy: 0.1000 - val_loss: 55317.3403 - val_accuracy: 0.0800
Epoch 4/10
1000/1000 [==============================] - 0s 65us/sample - loss: 63645.3235 - accuracy: 0.1080 - val_loss: 74619.0509 - val_accuracy: 0.1300
Epoch 5/10
1000/1000 [==============================] - 0s 60us/sample - loss: 81001.9045 - accuracy: 0.0970 - val_loss: 105868.2666 - val_accuracy: 0.0800
Epoch 6/10
1000/1000 [==============================] - 0s 62us/sample - loss: 114409.0335 - accuracy: 0.1130 - val_loss: 164796.9225 - val_accuracy: 0.0800
Epoch 7/10
1000/100

### Train from tf.data datasets
Use the Datasets API to scale to large datasets or multi-device training. Pass a tf.data.Dataset instance to the fit method:

In [24]:
# Instantiates a toy dataset instance:
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

model.fit(dataset, epochs=10)

Epoch 1/10
32/32 [==============================] - 0s 5ms/step - loss: 123703.0825 - accuracy: 0.1030
Epoch 2/10
32/32 [==============================] - 0s 2ms/step - loss: 106241.4956 - accuracy: 0.0990
Epoch 3/10
32/32 [==============================] - 0s 2ms/step - loss: 173562.8943 - accuracy: 0.0930
Epoch 4/10
32/32 [==============================] - 0s 3ms/step - loss: 205254.7680 - accuracy: 0.0890
Epoch 5/10
32/32 [==============================] - 0s 3ms/step - loss: 177919.0564 - accuracy: 0.1170
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 223075.0376 - accuracy: 0.0850
Epoch 7/10
32/32 [==============================] - 0s 2ms/step - loss: 177457.0407 - accuracy: 0.0950
Epoch 8/10
32/32 [==============================] - 0s 2ms/step - loss: 167000.0721 - accuracy: 0.1030
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 189559.0902 - accuracy: 0.0840
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 

Datasets can also be used for validation:

In [25]:
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

val_dataset = tf.data.Dataset.from_tensor_slices((val_data, val_labels))
val_dataset = val_dataset.batch(32)

model.fit(dataset, epochs=10,
          validation_data=val_dataset)

Epoch 1/10
32/32 [==============================] - 0s 4ms/step - loss: 359380.5967 - accuracy: 0.0990 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/10
32/32 [==============================] - 0s 2ms/step - loss: 345115.9201 - accuracy: 0.1040 - val_loss: 156944.9336 - val_accuracy: 0.1200
Epoch 3/10
32/32 [==============================] - 0s 3ms/step - loss: 225164.5492 - accuracy: 0.0950 - val_loss: 389806.0781 - val_accuracy: 0.1600
Epoch 4/10
32/32 [==============================] - 0s 2ms/step - loss: 303205.6797 - accuracy: 0.1120 - val_loss: 209036.5039 - val_accuracy: 0.0800
Epoch 5/10
32/32 [==============================] - 0s 3ms/step - loss: 294900.3774 - accuracy: 0.0900 - val_loss: 265484.1953 - val_accuracy: 0.0700
Epoch 6/10
32/32 [==============================] - 0s 3ms/step - loss: 351249.5470 - accuracy: 0.1050 - val_loss: 380213.3672 - val_accuracy: 0.0800
Epoch 7/10
32/32 [==============================] - 0s 3ms/step - loss: 402041.9904 - accuracy: 0

### Evaluate and predict

In [27]:
# With Numpy arrays
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.evaluate(data, labels, batch_size=32)

1000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[572681.335, 0.092]

In [28]:
# With a Dataset
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

model.evaluate(dataset)

32/32 [==============================] - 0s 958us/step - loss: 572683.1934 - accuracy: 0.0920


[572683.193359375, 0.092]

In [29]:
result = model.predict(data, batch_size=32)
print(result.shape)

(1000, 10)


## Build complex models--The Functional API
The tf.keras.Sequential model is a simple stack of layers that cannot represent arbitrary models. Use the Keras functional API to build complex model topologies such as:

* Multi-input models,
* Multi-output models,
* Models with shared layers (the same layer called several times),
* Models with non-sequential data flows (e.g. residual connections).

Building a model with the functional API works like this:

1. A layer instance is callable and returns a tensor.
1. Input tensors and output tensors are used to define a tf.keras.Model instance.
1. This model is trained just like the Sequential model.

In [30]:
inputs = tf.keras.Input(shape=(32,))  # Returns an input placeholder

# A layer instance is callable on a tensor, and returns a tensor.
x = layers.Dense(64, activation='relu')(inputs)
x = layers.Dense(64, activation='relu')(x)
predictions = layers.Dense(10, activation='softmax')(x)

In [31]:
model = tf.keras.Model(inputs=inputs, outputs=predictions)

# The compile step specifies the training configuration.
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Trains for 5 epochs
model.fit(data, labels, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 1s 501us/sample - loss: 13.6575 - accuracy: 0.0960
Epoch 2/5
1000/1000 [==============================] - 0s 50us/sample - loss: 22.3767 - accuracy: 0.0920
Epoch 3/5
1000/1000 [==============================] - 0s 49us/sample - loss: 35.9141 - accuracy: 0.0860
Epoch 4/5
1000/1000 [==============================] - 0s 44us/sample - loss: 52.3935 - accuracy: 0.1030
Epoch 5/5
1000/1000 [==============================] - 0s 50us/sample - loss: 72.4794 - accuracy: 0.1010


### Model subclassing

In [32]:
class MyModel(tf.keras.Model):

  def __init__(self, num_classes=10):
    super(MyModel, self).__init__(name='my_model')
    self.num_classes = num_classes
    # Define your layers here.
    self.dense_1 = layers.Dense(32, activation='relu')
    self.dense_2 = layers.Dense(num_classes, activation='sigmoid')

  def call(self, inputs):
    # Define your forward pass here,
    # using layers you previously defined (in `__init__`).
    x = self.dense_1(inputs)
    return self.dense_2(x)

In [33]:
# Instantiate the new model class:
model = MyModel(num_classes=10)

# The compile step specifies the training configuration.
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Trains for 5 epochs.
model.fit(data, labels, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 1s 1ms/sample - loss: 11.4251 - accuracy: 0.0890
Epoch 2/5
1000/1000 [==============================] - 0s 53us/sample - loss: 11.4008 - accuracy: 0.1030
Epoch 3/5
1000/1000 [==============================] - 0s 52us/sample - loss: 11.3957 - accuracy: 0.1120
Epoch 4/5
1000/1000 [==============================] - 0s 50us/sample - loss: 11.3928 - accuracy: 0.1060
Epoch 5/5
1000/1000 [==============================] - 0s 61us/sample - loss: 11.3915 - accuracy: 0.1100


### Custom layers
Create a custom layer by subclassing tf.keras.layers.Layer and implementing the following methods:

* `__init__`: Optionally define sublayers to be used by this layer.
* build: Create the weights of the layer. Add weights with the add_weight method.
* call: Define the forward pass.
* Optionally, a layer can be serialized by implementing the get_config method and the from_config class method.

Here's an example of a custom layer that implements a matmul of an input with a kernel matrix:

In [34]:
class MyLayer(layers.Layer):

  def __init__(self, output_dim, **kwargs):
    self.output_dim = output_dim
    super(MyLayer, self).__init__(**kwargs)

  def build(self, input_shape):
    # Create a trainable weight variable for this layer.
    self.kernel = self.add_weight(name='kernel',
                                  shape=(input_shape[1], self.output_dim),
                                  initializer='uniform',
                                  trainable=True)

  def call(self, inputs):
    return tf.matmul(inputs, self.kernel)

  def get_config(self):
    base_config = super(MyLayer, self).get_config()
    base_config['output_dim'] = self.output_dim
    return base_config

  @classmethod
  def from_config(cls, config):
    return cls(**config)

In [35]:
# Create a model using your custom layer:
model = tf.keras.Sequential([
    MyLayer(10),
    layers.Activation('softmax')])

# The compile step specifies the training configuration
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Trains for 5 epochs.
model.fit(data, labels, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 292us/sample - loss: 11.4139 - accuracy: 0.1060
Epoch 2/5
1000/1000 [==============================] - 0s 41us/sample - loss: 11.4144 - accuracy: 0.1070
Epoch 3/5
1000/1000 [==============================] - 0s 46us/sample - loss: 11.4143 - accuracy: 0.1070
Epoch 4/5
1000/1000 [==============================] - 0s 47us/sample - loss: 11.4145 - accuracy: 0.1080
Epoch 5/5
1000/1000 [==============================] - 0s 46us/sample - loss: 11.4137 - accuracy: 0.1070


## backend
封装了很多数学函数和方法

In [12]:
from tensorflow.keras import backend as K

In [8]:
import numpy as np

In [9]:
x = np.arange(8).reshape((2, 4))

In [10]:
np.expand_dims(x, 2)

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

In [13]:
K.expand_dims(x, 2)

<tf.Tensor: id=2, shape=(2, 4, 1), dtype=int64, numpy=
array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])>

In [14]:
K.one_hot(x, 10)

<tf.Tensor: id=7, shape=(2, 4, 10), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]], dtype=float32)>

In [15]:
K.permute_dimensions(x, (1, 0))

<tf.Tensor: id=10, shape=(4, 2), dtype=int64, numpy=
array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])>