In [13]:
# !pip install tensorflow -U
!pip freeze | grep tensorflow

tensorflow==2.1.0
tensorflow-datasets==1.3.0
tensorflow-estimator==2.1.0
tensorflow-metadata==0.15.0


In [14]:
import tensorflow as tf

# tf2相对于tf1的改进
https://tensorflow.google.cn/guide/effective_tf2
## API Cleanup
Many APIs are either gone or moved in TF 2.0. Some of the major changes include removing tf.app, tf.flags, and tf.logging in favor of the now open-source absl-py, rehoming projects that lived in tf.contrib, and cleaning up the main tf.* namespace by moving lesser used functions into subpackages like tf.math. Some APIs have been replaced with their 2.0 equivalents - tf.summary, tf.keras.metrics, and tf.keras.optimizers.
## Eager execution

In Tensorflow 2.0, eager execution is enabled by default.

In [2]:
tf.executing_eagerly()

True

## No more globals

## Functions, not sessions


# Eager execution
https://tensorflow.google.cn/guide/eager

TensorFlow的立即执行(Eager execution)是一种命令式编程环境，它可以立即计算操作，而不需要构建图形:操作返回具体的值，而不是构建一个计算图形以供以后运行。这使得开始使用TensorFlow和调试模型变得很容易，同时也减少了样板文件(boilerplate)。z

In [4]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


# tf计算

In [ ]:
tf.reduce_sum()

In [ ]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x)  # 6
tf.reduce_sum(x, 0)  # [2, 2, 2]
tf.reduce_sum(x, 1)  # [3, 3]
tf.reduce_sum(x, 1, keepdims=True)  # [[3], [3]]
tf.reduce_sum(x, [0, 1])  # 6

# backend
封装了很多数学函数和方法

In [1]:
from tensorflow.keras import backend as K

In [3]:
import numpy as np

In [4]:
x = np.arange(8).reshape((2, 4))

In [10]:
np.expand_dims(x, 2)

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

## expand_dims

In [13]:
K.expand_dims(x, 2)

<tf.Tensor: id=2, shape=(2, 4, 1), dtype=int64, numpy=
array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])>

## one_hot

In [14]:
K.one_hot(x, 10)

<tf.Tensor: id=7, shape=(2, 4, 10), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]], dtype=float32)>

## permute_dimensions

In [5]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
# 坐标轴置换
K.permute_dimensions(x, (1, 0))

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])>

## K.set_learning_phase()

keras.backend.set_learning_phase(0) # train mode

keras.backend.set_learning_phase(1) # predict mode

之所以这么区分，是因为某些层在预测和训练时不同

In [7]:
K.set_learning_phase(True)

In [8]:
K.learning_phase()

True