In [9]:
# !pip install tensorflow -U
!pip freeze | grep tensorflow

tensorflow==2.0.0
tensorflow-estimator==2.0.1


# tf2相对于tf1的改进
https://tensorflow.google.cn/guide/effective_tf2
## API Cleanup
Many APIs are either gone or moved in TF 2.0. Some of the major changes include removing tf.app, tf.flags, and tf.logging in favor of the now open-source absl-py, rehoming projects that lived in tf.contrib, and cleaning up the main tf.* namespace by moving lesser used functions into subpackages like tf.math. Some APIs have been replaced with their 2.0 equivalents - tf.summary, tf.keras.metrics, and tf.keras.optimizers.
## Eager execution
In Tensorflow 2.0, eager execution is enabled by default.
## No more globals

## Functions, not sessions




# backend
封装了很多数学函数和方法

In [12]:
from tensorflow.keras import backend as K

In [8]:
import numpy as np

In [9]:
x = np.arange(8).reshape((2, 4))

In [10]:
np.expand_dims(x, 2)

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

In [13]:
K.expand_dims(x, 2)

<tf.Tensor: id=2, shape=(2, 4, 1), dtype=int64, numpy=
array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])>

In [14]:
K.one_hot(x, 10)

<tf.Tensor: id=7, shape=(2, 4, 10), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]], dtype=float32)>

In [15]:
K.permute_dimensions(x, (1, 0))

<tf.Tensor: id=10, shape=(4, 2), dtype=int64, numpy=
array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])>