In [1]:
import autodiff as ad
import numpy as np

In [2]:
x2 = ad.Variable(name="x2")
y = x2

grad_x2, = ad.gradients(y, [x2])

executor = ad.Executor([y, grad_x2])
x2_val = 2 * np.ones(3)
y_val, grad_x2_val = executor.run(feed_dict={x2: x2_val})

In [13]:
y_val, grad_x2_val

(array([2., 2., 2.]), array([1., 1., 1.]))

In [3]:
print(ad.gradients(y, [x2]))

In [2]:
# 定义输入
x2 = ad.Variable(name = "x2")
x3 = ad.Variable(name = "x3")
# 画图
y = x2 + x3

## gradients 自动求微分

In [3]:
x2

In [4]:
x3

In [5]:
y

In [6]:
grad_x2, grad_x3 = ad.gradients(y, [x2, x3])

{<autodiff.Node object at 0x10e3ff3c8>: [<autodiff.Node object at 0x10e3ffac8>]} Oneslike((x2+x3))
{<autodiff.Node object at 0x10e3ff3c8>: [<autodiff.Node object at 0x10e3ffac8>], <autodiff.Node object at 0x10e3ff320>: [<autodiff.Node object at 0x10e3ffac8>], <autodiff.Node object at 0x10e3ff358>: [<autodiff.Node object at 0x10e3ffac8>]} Oneslike((x2+x3))
{<autodiff.Node object at 0x10e3ff3c8>: [<autodiff.Node object at 0x10e3ffac8>], <autodiff.Node object at 0x10e3ff320>: [<autodiff.Node object at 0x10e3ffac8>], <autodiff.Node object at 0x10e3ff358>: [<autodiff.Node object at 0x10e3ffac8>]} Oneslike((x2+x3))


In [4]:
grad_x2

In [8]:
executor = ad.Executor([y, grad_x2, grad_x3])
executor

In [9]:
x2_val = 2 * np.ones(3)
x3_val = 3 * np.ones(3)
x2_val

array([2., 2., 2.])

In [10]:
y_val, grad_x2_val, grad_x3_val = executor.run(feed_dict = {x2: x2_val, x3: x3_val})

In [11]:
y_val, grad_x2_val, grad_x3_val

(array([5., 5., 5.]), array([1., 1., 1.]), array([1., 1., 1.]))