## 标准化

In [2]:
from sklearn.preprocessing import normalize
from sklearn.preprocessing import StandardScaler

In [3]:
import numpy as np

In [8]:
x = np.arange(-4, 5).reshape((3, 3))
x

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

### 最大值置为1（除以最大值）

In [9]:
normalize(x, 'max')

array([[ 2.  ,  1.5 ,  1.  ],
       [-1.  ,  0.  ,  1.  ],
       [ 0.5 ,  0.75,  1.  ]])

In [10]:
normalize(x, 'max', axis=0)

array([[-2.  , -1.  , -0.5 ],
       [-0.5 ,  0.  ,  0.25],
       [ 1.  ,  1.  ,  1.  ]])

### 元素绝对值和为1

In [11]:
normalize(x, 'l1', axis=0)

array([[-0.57142857, -0.5       , -0.28571429],
       [-0.14285714,  0.        ,  0.14285714],
       [ 0.28571429,  0.5       ,  0.57142857]])

### 元素平方和为1

In [12]:
normalize(x, 'l2', axis=0)

array([[-0.87287156, -0.70710678, -0.43643578],
       [-0.21821789,  0.        ,  0.21821789],
       [ 0.43643578,  0.70710678,  0.87287156]])

### 均值为0，方差为1

In [13]:
StandardScaler().fit_transform(x)

/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])